# Generated by Django 2.0.2 on 2018-08-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20180812_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(height_field=400, upload_to='images/', width_field=400),
        ),
    ]
