# Generated by Django 2.0.2 on 2018-08-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Body', models.CharField(max_length=250)),
                ('Image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
