# Generated by Django 2.0.2 on 2018-08-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Date',
            field=models.DateTimeField(),
        ),
    ]
